### ISSUE TITLE
Convert VideoPress shortcodes to local media library file references

### ISSUE THREAD

**Issue by ChrisHardie** [a8cteam51/wordpress-importer-fixers#10]
Exporting a site with VideoPress on it includes WXR items for the original video files, which can then be imported from the VideoPress-served URL in to the local media library.

But, for any imported post content using the VideoPress shortcode, the shortcode remains and is converted back in to the VideoPress-served URL, not the local media library one. While VideoPress videos will be served indefinitely even if there's not an active subscription, some sites may want to make video storage and serving self-contained.

Since the video attachment item in the export WXR should include a parent post ID, we should be able to do a post-import fixer here. For each post with one and only one VideoPress shortcode, look up the attachment that has that post's ID as its parent, and then replace the VideoPress shortcode with a normal video embed/display/link reference.

**Comment by whyisjake** [comment]
Kinda have a quick fix here: 

```
add_shortcode('wpvideo', function($args) {
    $videos = get_attached_media('video');
    return implode( "\r\r", array_map( function( $video ) {
        return ! empty( $video->guid ) ? do_shortcode( sprintf( '[video src=%s]', $video->guid ) ) : "";
    }, $videos ) );
});
```

Without a proper 1:1 match on the shortcode, we would need to do some kind of API request to VideoPress, and the match the filename for the response.

**Comment by sanketio** [comment]
@ChrisHardie 

Do I need a premium plan for VideoPress testing? Because I think there is no way I can access VideoPress.

**Comment by ChrisHardie** [comment]
> Do I need a premium plan for VideoPress testing? Because I think there is no way I can access VideoPress.

Please let me know in Slack what site you want to test it on and I can set that up.

Also, @whyisjake do you have any updated recommendations on how to handle this in the generic case given the additional work you did?

**Comment by whyisjake** [comment]
You could try using this plugin that I wrote.

https://github.com/Automattic/videopress-local-import

**Comment by ChrisHardie** [comment]
@sanketio given the existence of a plugin to solve this, I'll go ahead and close this issue out for now.
