### ISSUE TITLE
be more defensive around download_url() errors

### ISSUE THREAD

**Issue by mdrovdahl** [a8cteam51/wordpress-importer-fixers#11]
`wp import-fixer import-external-images --domain=cdn-images-1.medium.com` is failing for me (with eg: https://cdn-images-1.medium.com/max/400/1*36EGqSSNy2hZOr59pGDY4w.png) b/c the response code is a 403 [here](https://core.trac.wordpress.org/browser/tags/4.9.8/src/wp-admin/includes/file.php#L976) but then gets reported as a 404 [here](https://core.trac.wordpress.org/browser/tags/4.9.8/src/wp-admin/includes/file.php#L985) as it's passed back up the stack and finally shows as an upload error: "File is empty. Please upload something more substantial. This error could also be caused by uploads being disabled in your php.ini or by post_max_size being defined as smaller than upload_max_filesize in php.ini."

We should probably be more defensive around here and bail on download (http) errors before falsely reporting it as an upload error https://github.com/a8cteam51/wordpress-importer-fixers/blob/master/import-fixer.php#L737

Related, can't figure out why the wp-cli is getting a 403 when I can curl the image url just fine...

`array(6) {
  'headers' =>
  class Requests_Utility_CaseInsensitiveDictionary#2878 (1) {
    protected $data =>
    array(13) {
      'date' =>
      string(29) "Tue, 27 Nov 2018 21:50:20 GMT"
      'content-type' =>
      string(24) "text/html; charset=UTF-8"
      'set-cookie' =>
      string(127) "__cfduid=dee95fc276303629ca87ff6a4fefc1d5d1543355420; expires=Wed, 27-Nov-19 21:50:20 GMT; path=/; domain=.medium.com; HttpOnly"
      'cache-control' =>
      string(10) "max-age=15"
      'expires' =>
      string(29) "Tue, 27 Nov 2018 21:50:35 GMT"
      'x-frame-options' =>
      string(10) "SAMEORIGIN"
      'strict-transport-security' =>
      string(44) "max-age=15552000; includeSubDomains; preload"
      'x-content-type-options' =>
      string(7) "nosniff"
      'expect-ct' =>
      string(87) "max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct""
      'vary' =>
      string(15) "Accept-Encoding"
      'server' =>
      string(10) "cloudflare"
      'cf-ray' =>
      string(20) "4807cf4f4d00bc80-SEA"
      'content-encoding' =>
      string(4) "gzip"
    }
  }
  'body' =>
  string(0) ""
  'response' =>
  array(2) {
    'code' =>
    int(403)
    'message' =>
    string(9) "Forbidden"
  }
  'cookies' =>
  array(1) {
    [0] =>
    class WP_Http_Cookie#2873 (5) {
      public $name =>
      string(8) "__cfduid"
      public $value =>
      string(43) "dee95fc276303629ca87ff6a4fefc1d5d1543355420"
      public $expires =>
      int(1574891420)
      public $path =>
      string(1) "/"
      public $domain =>
      string(10) "medium.com"
    }
  }
  'filename' =>
  string(39) "/tmp/136EGqSSNy2hZOr59pGDY4w-b1FOib.tmp"
  'http_response' =>
  class WP_HTTP_Requests_Response#2869 (5) {
    protected $response =>
    class Requests_Response#2882 (10) {
      public $body =>
      string(0) ""
      public $raw =>
      string(686) "HTTP/1.1 403 Forbidden
Date: Tue, 27 Nov 2018 21:50:20 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: close
Set-Cookie: __cfduid=dee95fc276303629ca87ff6a4fefc1d5d1543355420; expires=Wed, 27-Nov-19 21:50:20 GMT; path=/; domain=.medium.com; HttpOnly
Cache-Control: max-age=15
Expires: Tue, 27 Nov 2018 21:50:35 GMT
X-Frame-Options: SAMEORIGIN
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Expect-CT: max-age=60"...
      public $headers =>
      class Requests_Response_Headers#2870 (1) {
        ...
      }
      public $status_code =>
      int(403)
      public $protocol_version =>
      double(1.1)
      public $success =>
      bool(false)
      public $redirects =>
      int(0)
      public $url =>
      string(68) "https://cdn-images-1.medium.com/max/400/1*36EGqSSNy2hZOr59pGDY4w.png"
      public $history =>
      array(0) {
        ...
      }
      public $cookies =>
      class Requests_Cookie_Jar#2885 (1) {
        ...
      }
    }
    protected $filename =>
    string(39) "/tmp/136EGqSSNy2hZOr59pGDY4w-b1FOib.tmp"
    public $data =>
    NULL
    public $headers =>
    NULL
    public $status =>
    NULL
  }
}
`
`Marks-MBP:wp-signalvnoise-blog markd$ curl -Ivvv https://cdn-images-1.medium.com/max/400/1*36EGqSSNy2hZOr59pGDY4w.png
*   Trying 104.16.117.145...
* TCP_NODELAY set
* Connected to cdn-images-1.medium.com (104.16.117.145) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/cert.pem
  CApath: none
* TLSv1.2 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (IN), TLS handshake, Server finished (14):
* TLSv1.2 (OUT), TLS handshake, Client key exchange (16):
* TLSv1.2 (OUT), TLS change cipher, Client hello (1):
* TLSv1.2 (OUT), TLS handshake, Finished (20):
* TLSv1.2 (IN), TLS change cipher, Client hello (1):
* TLSv1.2 (IN), TLS handshake, Finished (20):
* SSL connection using TLSv1.2 / ECDHE-RSA-CHACHA20-POLY1305
* ALPN, server accepted to use h2
* Server certificate:
*  subject: C=US; ST=California; L=San Francisco; O=A Medium Corporation; CN=*.medium.com
*  start date: Jul 31 00:00:00 2018 GMT
*  expire date: Sep  9 12:00:00 2020 GMT
*  subjectAltName: host "cdn-images-1.medium.com" matched cert's "*.medium.com"
*  issuer: C=US; O=DigiCert Inc; CN=DigiCert SHA2 Secure Server CA
*  SSL certificate verify ok.
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fe250808800)
> HEAD /max/400/1*36EGqSSNy2hZOr59pGDY4w.png HTTP/2
> Host: cdn-images-1.medium.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
HTTP/2 200 
< date: Tue, 27 Nov 2018 21:54:30 GMT
date: Tue, 27 Nov 2018 21:54:30 GMT
< content-type: image/png
content-type: image/png
< content-length: 499995
content-length: 499995
< set-cookie: __cfduid=dcc664a1c3da449aed068d0bfb7773fed1543355669; expires=Wed, 27-Nov-19 21:54:29 GMT; path=/; domain=.medium.com; HttpOnly
set-cookie: __cfduid=dcc664a1c3da449aed068d0bfb7773fed1543355669; expires=Wed, 27-Nov-19 21:54:29 GMT; path=/; domain=.medium.com; HttpOnly
< access-control-allow-origin: *
access-control-allow-origin: *
< cache-control: public, max-age=2592000
cache-control: public, max-age=2592000
< etag: "16.3"
etag: "16.3"
< expires: Thu, 27 Dec 2018 21:54:30 GMT
expires: Thu, 27 Dec 2018 21:54:30 GMT
< pragma: public
pragma: public
< x-obvious-info: 16.3, 3181-1a71b1f
x-obvious-info: 16.3, 3181-1a71b1f
< x-powered-by: Geomyidae artificij
x-powered-by: Geomyidae artificij
< strict-transport-security: max-age=15552000; includeSubDomains; preload
strict-transport-security: max-age=15552000; includeSubDomains; preload
< cf-cache-status: MISS
cf-cache-status: MISS
< accept-ranges: bytes
accept-ranges: bytes
< x-content-type-options: nosniff
x-content-type-options: nosniff
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< server: cloudflare
server: cloudflare
< cf-ray: 4807d567de00bb48-SEA
cf-ray: 4807d567de00bb48-SEA

< 
* Connection #0 to host cdn-images-1.medium.com left intact
`

**Comment by mdrovdahl** [comment]
Good fix- I don't think it's toooo sleazy and there's precedence for it in other importers.

**Comment by sanketio** [comment]
@mdrovdahl: Is anything required here?

I think @wpalchemist already updated that function here - https://github.com/a8cteam51/wordpress-importer-fixers/blob/master/import-fixer.php#L808-L832

So not sure what needs to be done here.

cc: @ChrisHardie @wrightcj03

**Comment by wrightcj03** [comment]
Adding @pippercameron to help with next steps here.

**Comment by pippercameron** [comment]
@sanketio I think you're right that the fix mentioned above is already implemented, but I'm not sure what this part means:

>Unfortunately, it gets the actual raw image, instead of a file that can be inserted into the media library, but we could work around that if needed.

I think we can close this out for now and revisit later if necessary.
